// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.1.0.0
//      SpecFlow Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace PayCoreApiTest.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.1.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("payouts")]
    public partial class PayoutsFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "payouts.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "payouts", null, ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("C14456 Verify Full screen in a new tab on Mini Game Modal")]
        public virtual void C14456VerifyFullScreenİnANewTabOnMiniGameModal()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("C14456 Verify Full screen in a new tab on Mini Game Modal", ((string[])(null)));
#line 3
 this.ScenarioSetup(scenarioInfo);
#line 5
 testRunner.And("Driver\'i ayaga kaldir", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 6
 testRunner.And("https://mybookie-engine.qa.jetu.cr/ adresine git", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 7
 testRunner.And("menuLogin elementine tikla", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 8
 testRunner.And("accountNumber elementine MB2223781 textini yaz", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 9
 testRunner.And("accountPassword elementine Mb123456789* textini yaz", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 10
 testRunner.And("loginBtn elementine tikla", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 11
 testRunner.And("menuSportsbookActive elementinin varligi kontrol edilir", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 12
 testRunner.And("cashierButton elementine tikla", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 13
 testRunner.And("Check the URL Contains Contains The cashier/deposit Value", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 14
 testRunner.And("payoutButton elementine tikla", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 15
 testRunner.And("Is The Color Of The Element payoutButton Orange", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 16
 testRunner.And("miniGamesModal elementinin görünürlüğü kontrol edilir", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 17
 testRunner.And("miniGamesModal elementine tikla", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 18
 testRunner.And("miniGameModalNewTab elementine tikla", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 19
 testRunner.And("modalNewTabDialog elementinin görünürlüğü kontrol edilir", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 20
 testRunner.And("dialogYesButton elementine tikla", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 21
 testRunner.And("Son Sekmeye Odaklan", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 22
 testRunner.And("Check the URL Contains Contains The discreetgaming Value", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("14457 Verify Full Screen Icon Mini Game Modal")]
        public virtual void _14457VerifyFullScreenIconMiniGameModal()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("14457 Verify Full Screen Icon Mini Game Modal", ((string[])(null)));
#line 26
 this.ScenarioSetup(scenarioInfo);
#line 28
 testRunner.And("Driver\'i ayaga kaldir", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 29
 testRunner.And("https://mybookie-engine.qa.jetu.cr/ adresine git", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 30
 testRunner.And("menuLogin elementine tikla", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 31
 testRunner.And("accountNumber elementine MB2223781 textini yaz", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 32
 testRunner.And("accountPassword elementine Mb123456789* textini yaz", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 33
 testRunner.And("loginBtn elementine tikla", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 34
 testRunner.And("menuSportsbookActive elementinin varligi kontrol edilir", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 35
 testRunner.And("cashierButton elementine tikla", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 36
 testRunner.And("Check the URL Contains Contains The cashier/deposit Value", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 37
 testRunner.And("payoutButton elementine tikla", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 38
 testRunner.And("Is The Color Of The Element payoutButton Orange", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 39
 testRunner.And("miniGamesModal elementinin görünürlüğü kontrol edilir", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 40
 testRunner.And("miniGamesModal elementine tikla", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 41
 testRunner.And("miniGameModalFullScreen elementine tikla", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 42
 testRunner.And("fullScreenGame elementinin görünürlüğü kontrol edilir", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("C14458 Verify Expand / collapse Mini Game Modal")]
        public virtual void C14458VerifyExpandCollapseMiniGameModal()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("C14458 Verify Expand / collapse Mini Game Modal", ((string[])(null)));
#line 45
 this.ScenarioSetup(scenarioInfo);
#line 47
 testRunner.And("Driver\'i ayaga kaldir", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 48
 testRunner.And("https://mybookie-engine.qa.jetu.cr/ adresine git", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 49
 testRunner.And("menuLogin elementine tikla", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 50
 testRunner.And("accountNumber elementine MB2223781 textini yaz", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 51
 testRunner.And("accountPassword elementine Mb123456789* textini yaz", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 52
 testRunner.And("loginBtn elementine tikla", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 53
 testRunner.And("menuSportsbookActive elementinin varligi kontrol edilir", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 54
 testRunner.And("cashierButton elementine tikla", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 55
 testRunner.And("Check the URL Contains Contains The cashier/deposit Value", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 56
 testRunner.And("payoutButton elementine tikla", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 57
 testRunner.And("Is The Color Of The Element payoutButton Orange", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 58
 testRunner.And("miniGamesModal elementinin görünürlüğü kontrol edilir", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 59
 testRunner.And("miniGameCollapseIcon elementine tikla", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("C14459 Mini Game Launches")]
        public virtual void C14459MiniGameLaunches()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("C14459 Mini Game Launches", ((string[])(null)));
#line 63
 this.ScenarioSetup(scenarioInfo);
#line 64
 testRunner.And("Driver\'i ayaga kaldir", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 65
 testRunner.And("https://mybookie-engine.qa.jetu.cr/ adresine git", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 66
 testRunner.And("menuLogin elementine tikla", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 67
 testRunner.And("accountNumber elementine MB2223781 textini yaz", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 68
 testRunner.And("accountPassword elementine Mb123456789* textini yaz", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 69
 testRunner.And("loginBtn elementine tikla", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 70
 testRunner.And("menuSportsbookActive elementinin varligi kontrol edilir", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 71
 testRunner.And("cashierButton elementine tikla", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 72
 testRunner.And("Check the URL Contains Contains The cashier/deposit Value", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 73
 testRunner.And("payoutButton elementine tikla", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 74
 testRunner.And("Is The Color Of The Element payoutButton Orange", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 75
 testRunner.And("miniGamesModal elementinin görünürlüğü kontrol edilir", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 76
 testRunner.And("miniGamesModal elementine tikla", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
